### ISSUE TITLE
[feature request] add support for enterprise routes

### ISSUE THREAD

**Issue by JordanSussman** [swinton/github-rest-apis-for-insomnia#27]
I occasionally run into situations where the [api.github.com](https://github.com/octokit/routes/tree/master/cache/api.github.com) routes aren't sufficient enough when working with GHE, so it would be great if you considered adding at least the latest version of the [GHE](https://github.com/octokit/routes/tree/master/cache/ghe-2.16) routes.

**Comment by IAmHughes** [comment]
To grab the GitHub Enterprise Server (GHES) routes:
- https://octokit.github.io/routes/routes/ghe-2.16/index.json
- https://octokit.github.io/routes/routes/ghe-2.16/index.json
- https://octokit.github.io/routes/routes/ghe-2.17/index.json
- etc

Since we're already processing the octokit routes for the standard API, I assume this wouldn't be TOO difficult to implement. I may take this one on, /cc @swinton

**Comment by swinton** [comment]
Working on it in #45.

**Comment by swinton** [comment]
Enterprise routes are now generated for all currently supported versions of GitHub Enterprise Server:

https://github.com/swinton/github-rest-apis-for-insomnia/tree/master/routes
